### ISSUE TITLE
MAJOR REI eating ram like no tomorrow

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#84]
When REI is enabled (shown) ram usage climbs at a rate of roughly 50mb / second.

**Comment by ghost** [comment]
Seems to be affected by FPS, so render method might be a good place to look first.

**Comment by shedaniel** [comment]
Shoot the worst has came
I will look into this asap

**Comment by shedaniel** [comment]
oH n0e IT Is The end OF reI I cAnNOT fiX ThiS

**Comment by edeetee** [comment]
I get lags when I use this with [Materialisation](https://minecraft.curseforge.com/projects/materialisation).

I think it could be related to this?

My thoughts already is that possibly textures are loaded for all items, not just the items on the current page?

**Comment by shedaniel** [comment]
No, the lag should be fixed in the latest REI version, I have noticed the extreme lag with REI while developing Materialisation too but it is now been fixed.

**Comment by edeetee** [comment]
I'm still getting it after updating to the latest version on Forge.

**Comment by shedaniel** [comment]
Forge? I am mishearing stuff?

**Comment by edeetee** [comment]
curseforge, the website.

**Comment by shedaniel** [comment]
REI should be better in v2.9.8, I am seeing ram performance similar to vanilla, please test on that version. 

Ugh REI is not building (it is erroring) rn so it is not uploaded

**Comment by shedaniel** [comment]
v2.9.8 Build 149 is now on CF, with less ram usage.

**Comment by shedaniel** [comment]
Mostly ram usage is fixed, but the extra ram usage are the item stacks instances.
