### ISSUE TITLE
[Bug] [2.8.2.104] - Crash on load. 

### ISSUE THREAD

**Issue by JaSpr** [shedaniel/RoughlyEnoughItems#87]
**Describe the bug**
After installing REI 2.8.2.104, my game crashes as soon as it starts.  It does not crash when I revert to 103.  Tried switching back and forth multiple times. Always crashes with 104

**Steps to Reproduce**
Add mod v104
Start Game
Game crashes

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14
 - Mod Loader: Fabric 1.14+build.7-0.4.6+build.141

**Logs**
[Crash log](https://gist.github.com/JaSpr/d9209a270483b5df88017e36e15b8baa)

**Additional context**
Mods loaded and stuff
<img width="798" alt="Screen Shot 2019-05-07 at 7 51 46 PM" src="https://user-images.githubusercontent.com/1010443/57341981-1fdd9780-7102-11e9-80e4-6807c4fb7aa5.png">
<img width="862" alt="Screen Shot 2019-05-07 at 7 50 45 PM" src="https://user-images.githubusercontent.com/1010443/57341985-22d88800-7102-11e9-8554-12a1201d998d.png">

**Comment by shedaniel** [comment]
Found the crash reason, it is only reproducible on macOS.

**Comment by JaSpr** [comment]
Ah yes. I am on OsX :D

**Comment by shedaniel** [comment]
Can you test on build 106? I don't personally have a mac but I can't find the source of the bug so I doubt it has been fixed.

**Comment by JaSpr** [comment]
Issue still exists in 106.  [crash log](https://gist.github.com/JaSpr/ec83f0495a3c01b201a2ef9b51c7e09e)

**Comment by JaSpr** [comment]
[crash-2019-05-09_17.12.16-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/3164197/crash-2019-05-09_17.12.16-client.txt)

**Comment by JaSpr** [comment]
Still exists in 108
[crash-2019-05-11_12.09.14-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/3169283/crash-2019-05-11_12.09.14-client.txt)

**Comment by shedaniel** [comment]
Can you test with default plugin off? (it is in the config, use build 103 to disable it and test with build 108)
Thank you!

**Comment by gothkar** [comment]
> Can you test with default plugin off? (it is in the config, use build 103 to disable it and test with build 108)
> Thank you!

On OSX as well, with the same crash. Did not resolve the issue.
[crash.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/3169470/crash.txt)

**Comment by shedaniel** [comment]
Honestly, I can't find the bug. Build 104 is a small update and I kept looking into it.
Please try build 109, I removed one usage of OpenGL introduced by build 104 so it might help.

**Comment by gothkar** [comment]
Still doesn't work with 109 build. I'll just stay on 103 for awhile I guess. I wish you luck in finding it!

**Comment by shedaniel** [comment]
As the crash is related to OpenGL, I removed 1 more usage of OpenGL in build 110, please try it. (I doubt it will work tho)

**Comment by shedaniel** [comment]
Build 110 has been confirmed working on macOS! Please comment if this keep occurring, thanks to everyone who helped on this issue. <3
