### ISSUE TITLE
[Bug] Search Bar stopped working

### ISSUE THREAD

**Issue by Spider987** [shedaniel/RoughlyEnoughItems#984]
### What happened?

One of my players search bar randomly stopped working. I looked at the other post about this issue, and couldn't find the mod in our list. Mine currently works, and we made sure our settings for the mod was the same.

Is there a list of mods that could cause this? Or is this just a random bug?

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
No logs
```

### Anything else?

![image](https://user-images.githubusercontent.com/109045896/178164594-dc4a366d-dbb4-4ea4-a7ce-153889cad862.png)

**Comment by oitsjustjose** [comment]
Also experiencing this issue on Forge 40.1.60, REI (and REI JEI Internals Workaround) 8.3.510,

**Comment by Mari023** [comment]
the bug occurs on 8.3.495
it works properly on 8.2.492

**Comment by shedaniel** [comment]
I need logs, please send the latest.log

**Comment by oitsjustjose** [comment]
[Here you are](https://gist.github.com/oitsjustjose/78ef48e413e2942253d8989eb62465d7).

Don't mind the Tooltip errors - messed up a KubeJS Client Script. Can confirm that before I had these tooltip issues I still had a broken search.

**Comment by shedaniel** [comment]
The KubeJS issue is affecting REI however. Can you fix it, test REI search again and send a new log

**Comment by Spider987** [comment]
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9105232/rei.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9105233/latest.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9105235/rei-issues.log)

Here are the relevant logs from the player. Apologies for not posting earlier.

**Comment by shedaniel** [comment]
This should be fixed in the latest update.

**Comment by 854342681** [comment]
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10302782/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10302783/rei-issues.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10302785/latest.log)

I also meet this problem, and I don't know which mods make this problem, here are the relevant logs from the player.

minecraft version:
1.18.2

forge version:
40.1.86

mod version:
RoughlyEnoughItems-8.3.579

**Comment by KirpichKrasniy** [comment]
in modpack create astral of mods on versions REI 8.3.588 and 8.3.594 minecraft 1.18.2 search by name still does not work...
